name: UnitedRestoration
version: 0.0.1
main: org.unitedlands.restoration.UnitedRestoration
api-version: "26.2"
description: UnitedLands chunk restoration
author: Theriel_
depend: [UnitedLib]
softdepend: [UnitedLands, Towny]
